services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    environment:
      - xpack.security.enabled=false # for development only
      - discovery.type=single-node # for single node cluster
    networks:
      - elastic
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana
    ports:
      - 5601:5601
    restart: always
    volumes:
      - kibanadata:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic
  logstash:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    container_name: logstash
    ports:
      - 8080:8080
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/input:/usr/share/logstash/input
      - ./logstash/output:/usr/share/logstash/output
    restart: always
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    networks:
      - elastic
volumes:
  esdata:
  kibanadata:
networks:
  elastic:
    driver: bridge
